version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bicommerce-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bicommerce
      POSTGRES_USER: bicommerce_user
      POSTGRES_PASSWORD: bicommerce_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bicommerce_user -d bicommerce"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching (optional - can be added later if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: bicommerce-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  postgres_data:
  # redis_data: